[#20] 로그인 페이지 마크업 구현
woowacourse-teams/2021-tyf pull request #33
Opened 2021-07-08 07:38 UTC by hchayan

2021-07-08 07:39 UTC, hchayan commented on client/src/pages/Login/LoginPage.styles.ts
> +  // TODO: 아래와 같은 subText의 색상을 theme으로 설정해두면 이후 다크테마 구현에 적절할듯합니다
아래와 같은 subText의 색상을 theme으로 설정해두면 이후 다크테마 구현에 적절할듯합니다
(로그인 유지하기 Label 텍스트입니다)

2021-07-09 01:11 UTC, jho2301 commented on client/src/pages/Login/LoginPage.styles.ts
> +  // TODO: 아래와 같은 subText의 색상을 theme으로 설정해두면 이후 다크테마 구현에 적절할듯합니다
오 좋은듯

2021-07-09 01:15 UTC, jho2301 requested changes
리뷰남겼어 확인해줘~

2021-07-09 01:15 UTC, jho2301 commented on client/src/components/@molecule/ButtonWithIcon/ButtonWithIcon.tsx
> +}
ImgHTMLAttributes<HTMLImgElement>도 상속받는게 좋을 것 같아. 따로 명시해주지 않아서 좋을듯

2021-07-09 01:15 UTC, jho2301 commented on client/src/components/@molecule/OutlineButtonWithIcon/OutlineButtonWithIcon.styles.ts
> +  &:active {
사소한건데 블록마다 줄바꿈해주는거 어때???

2021-07-09 01:15 UTC, jho2301 commented on client/src/components/@molecule/OutlineButtonWithIcon/OutlineButtonWithIcon.tsx
> +}
위랑 똑같어

2021-07-09 01:34 UTC, hchayan commented on client/src/components/@molecule/ButtonWithIcon/ButtonWithIcon.tsx
> +}
천재야?

2021-07-09 01:35 UTC, merged