feat(client): 비회원 로그인시 회원가입, 회원 회원가입시 로그인 플로우 추가
woowacourse-teams/2021-tyf pull request #372
Opened 2021-09-28 11:21 UTC by hchayan

비회원이 로그인 시도시 경고창과 함께 바로 회원가입 수행
회원이 회원가입 시도시 경고창과 함께 바로 로그인 수행

2021-09-28 14:11 UTC, jho2301 requested changes
잘 된다. 굿굿

기존회원 로그인도 처리해버렸네

직접 동작하는 것 보니까 나쁘지 않은듯!

이슈 남겨준거 확인 부탁해용

2021-09-28 14:11 UTC, jho2301 commented on client/main/src/service/auth/useLoginEffect.ts
> +        alert('가입된 사용자가 아닙니다. 회원가입 절차로 이동합니다.');
멘트가 조금 딱딱한 거 같아서  아래 느낌으로 바꾸면 어때?

회원이 아닙니다.  회원가입 페이지로 이동합니다.

2021-09-28 14:11 UTC, jho2301 commented on client/main/src/service/auth/useRegisterOauthEffect.ts
> +      storeAccessToken(token);
이러면 다른 에러도 액세스토큰을 저장해버리지 않을까?

2021-09-28 16:04 UTC, hchayan commented on client/main/src/service/auth/useLoginEffect.ts
> +        alert('가입된 사용자가 아닙니다. 회원가입 절차로 이동합니다.');
원인과 해결방법을 명시해주고 싶어서 이렇게한건데, 너 말대로 좀더 유하게 해도 좋을듯 ㅇㅇ

2021-09-28 16:08 UTC, hchayan commented on client/main/src/service/auth/useRegisterOauthEffect.ts
> +      storeAccessToken(token);
으 로직 롤백하면서 해당 에러일때 처리하는 식으로 했던 부분이 없어졌었네

1차적으로 분기문으로 '이미 가입된 사용자' 일때 token을 사용하고,
이때 token이 없으면 /login 라우터로 이동하게끔 해놨어 👍

2021-09-29 03:58 UTC, jho2301 approved these changes

2021-09-29 03:59 UTC, merged