refactor(server): Member와 Creator로 분리한다, 후원 목록에 pageName도 함께준다.
woowacourse-teams/2021-tyf pull request #424
Opened 2021-09-30 15:35 UTC by Be-poz

커밋 내역 순서로 주안점을 말하겠음. 글이 좀 길어.. 그래도 읽으면 리뷰하기 편할거야  

Donation 필드 내에 있던 ``Member member`` 를 ``Member creator``, ``Member donator`` 로 분리했음  

![image](https://user-images.githubusercontent.com/45073750/135476391-c109136a-c922-4eb4-b1f4-4a260cdae44f.png)

그냥 이렇게 해도 분리되더라구. 지난번 실험 때에 안된다고 생각했던 이유는 해당 엔티티에 레이지 로딩을 해도 null을 유지했는데 이건 디버거의 문제였어. 원래 이전에는 레이지 로딩을 하면 디버거에서도 그 값이 채워지는게 보였는데 지금 이 상황 말고 일반적인 다른 상황에서도 다 null만 나오더라고.. ?? 그래서 이게 로딩이 된건지 안된건지 감이 안와서 ``getName()`` 같은 메서드로 일단 로딩을 시키고 다시 해당 메서드를 호출 했을 때에 로딩이 되었다면 select 쿼리가 안나갈테니깐 확인해보니 이미 안나가더라. 로딩이 된거였음.  

내가 저 방식이 안된다고 착각하게된 원인은 다음과 같아.

``ManyTo'One'`` 이라는 단어에 속음. DB에 Member테이블과 Donation테이블이 있음. Donation의 fk 컬럼에 member테이블의 id가 존재함. 하나의 Member에 여러 Donation들이 꽂힐 수가 있음. 일대다 관계임. 그런데 다른 fk 또한 가질 수 있음. 일반적인 경우 다른 테이블의 pk겠지만 이 상황에서는 또 다른 Member의 id 인거임. 이것 때문에 'One' 이 아니지 않나 라고 착각을 해버림. 하지만 잘 생각해보면 하나의 Member에 여러개의 Donation이 꽂힌다는 사실은 변함이 없음. 이 부분을 계속 헷갈려하고 착각했음. 하나의 Donation이 여러 개의 Member를 가지는 n:n 느낌도 어설프게 나긴하지만 fk로 갖고 있다는 점을 생각해야함.  

결론 : null의 이유는 디버거의 문제. 잘됨.  

분리를 하게되면서 하나의 Member타입 필드가 더 추가되었고, member라는 변수명이 사라지고 creator, donator가 추가되면서 굉장히 많은 메서드들의 네이밍이 변경되었음 커밋내역으로 확인바람. Member 내부에도 그냥 ``List<Donation> donations``에서 2개의 ``List<Donation>`` 으로 나뉘게됨.  

![image](https://user-images.githubusercontent.com/45073750/135481478-3e1845ef-42c0-4697-b479-5e250767de6f.png)

이렇게 나뉘게됨. 따지고보면 기존의 ``donations`` 필드는 받은 후원들이니 현재의 ``givenDonations``와 동일함.  
두 개의 네이밍 중에서 내가 준 도네이션에 대한 네이밍이 굉장히 애매했음. 일단 ``givingDonations``로 해둠  

<br/>

도네이션 메세지 작성 시에 nickName을 안보내게끔 api스펙을 바꿈. 프론트도 말하기도 했고 우리 회의록에도 적혀있어서 실행함  
해당 api는 ``/donations/{donationId}/messages`` 임. 이 API는 이전에 api 요청자와 도네이션의 주인에 대한 검증이 필요하다는 todo가 달린 api 였기에 같이 수행함. 안그래도 nickname에 대한 조회 떄문에 LoginMember를 파라미터에 추가했어야 했는데 todo의 내용도 동일했기에 겸사겸사 했음  

![image](https://user-images.githubusercontent.com/45073750/135482296-87394fa6-6cd9-45f1-89d9-67bc31ee6f0e.png)

그리고 ``MemberService``의 ``addMessageToDonation`` 메서드를 수정했음  
토큰에서 얻은 ``LoginMember``의 ``id`` 를 파라미터로 넘겨줘서 ``Member``를 찾고 이걸로 닉네임을 가져다가 쓰고,  
도네이션의 주인이 해당 멤버가 맞는지에 대한 로직을 추가함 확인바람.  

<br/>

``DonationResponse`` (후원 목록 return 할 때에 사용하는 response) 필드에 pageName 포함시킴  

기존의 response는 Donation 이 가진 필드로만 충분했기 때문에 다음과 같은 메서드를 이용했었음  
![image](https://user-images.githubusercontent.com/45073750/135483391-4ef0ae4f-29a8-43eb-a85d-8dddc3cb8313.png)

Donation만 딱 끌고왔었음. 네이밍으로 짠 쿼리고 너무 길어서 보기 싫었음. 그래서 이거를  
![image](https://user-images.githubusercontent.com/45073750/135483556-14596253-3317-4f81-80b6-403b723421e8.png)

이렇게 바로 dto 형식으로 뽑아오려고 시도했음. Donation은 쿼리로 찾아서 생성자에 넣어주고, Member의 pageName은 해당 메서드의 파라미터로 넘기고 그 파라미터를 생성자에 넣어주는 식으로  
![image](https://user-images.githubusercontent.com/45073750/135483820-da205157-7bf0-440a-b53b-d7a0aabbd78b.png)

대충 이런식으로! 근데 이게 불가능하다고 나왔음. 생성자에 들어가는 타입은 일반적인 String이 아니라 ``Expresstion<String>`` 이런식이더라고 잘 기억은 안나는데 앞에 Expression이 붙음. 쿼리를 통해 찾은 값만 가능함. 그래서 불가능했어.  

위 방식이 불가능하기도 했고, 후원 목록 로직 중에 secret이 체크되어 있는 것들은 내부 메세지를 숨겨야 하기 때문에  
![image](https://user-images.githubusercontent.com/45073750/135484134-139d5fdf-fe4e-423e-ac51-bd091c906111.png)

다음과 같은 메서드를 호출하고 있었는데 쿼리로 ``List<DonationResponse>`` 타입으로 받게되면 이 메서드를 사용못하게 되고 좀 복잡해지는 문제가 있더라고! 그래서 이걸 어쩌지 생각을 하다가  

![image](https://user-images.githubusercontent.com/45073750/135484931-d0ef9aba-8181-4e06-be4e-a5af7b25d74f.png)

이렇게 하게됨. 이렇게 간단할 수가... pageName 필드가 추가된 ``DonationResponse``는 내부에 ``Member``의 ``pageName``이 필요함. 그래서 그냥 ``Donation``을 갖고 올 때에 member를 페치조인해서 로딩시킨채로 끌고오는 방식을 택함.  
``@EntityGraph``는 어노테이션으로 페치조인을 쓸 때 쓰는 어노테이션임. ``JpaRepository``를 사용하면 보통 간단한건 네이밍으로 많이 처리하는데 페치 조인을 해야 한다는 이유로 ``@Query("select d from donation d join fetch d.member where...")`` 이거하기에 번거로우니깐 저렇게 처리하는거야. 참고로 ``@EntityGraph`` 이용시에는 left outer join이고, ``join fetch`` 이용시에는 inner join 으로 처리되니깐 유의해야함.  

어쨋든 ``Member`` 까지 끌고오면, ``DonationResponse`` 생성자로 ``Donation``만 보내고,  
![image](https://user-images.githubusercontent.com/45073750/135486365-3a1f41d9-c886-4e93-9480-9ac39afef438.png)

그 ``Donation`` 에서 ``donation.getCreator().getPageName()`` 식으로 호출하게끔 함. 페치조인으로 끌고왔으니깐 n+1 문제는 없음.  

![image](https://user-images.githubusercontent.com/45073750/135485633-25df6631-feac-48b5-a8e5-aa06bc455ee0.png)

요 뇨석들이 결국 삭제됨. 커밋으로 변경점 확인바람! 이 부분과 더불어 ``Donation``이 로키랑 겹쳐서 conflict 많이 날 것 같은데, 로키거는 로키 버전으로 일단 머지시키고 내가 pull 땡겨서 컨플릭 해결하고 갈게. 내쪽이 최신 요구사항 쪽이니깐 처리하고 가겠음  

<br/>

로직은 대략 이 정도고, 나머지는 Test 커밋들이야. Donation 필드를 고치니깐 기능되는대로 테스트 수정이 불가능해서 마지막에 한 번에 했어. ``DonationServiceTest`` 쪽을 특히 이전에 좀 부족했던 내용들과 더불어서 이번 내용합쳐서 쭉 고쳤으니깐 다른 테스트들은 그냥 넘기더라도 이 테스트들은 하나씩 흐름 따라가면서 파악하면 이번 PR 내용 이해하는데에 큰 도움될 것 같음!!  

긴 코멘트 읽어줘서 땡큐!

2021-10-01 06:00 UTC, DWL5 requested changes
저번에 디버거 때문에 약간 삽질이 있었구먼... 결론적으로 잘 해결되서 다행!
donation이 donator와 creator를 가질 수 있게되어서
이번 회원가입에 대한 요구사항 변경이 잘 반영된 느낌이야!!!

일단 저번에 회의로 로직 말한것 잘 반영해준것 같아 이해하기 쉽도록 PR 메시지도 상세히 작성해주고!!
몇가지 코멘트 남겼고, 로키 PR머지되어서 충돌난거 반영하면 한번 더 코드비류 할게!

2021-10-01 06:14 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/repository/DonationRepository.java
> -    List<Donation> findFirst5ByMemberAndStatusNotOrderByCreatedAtDesc(Member member, DonationStatus status);
사라졌으 ``DonationService`` 에서 다른 메서드로 대체되고 있으니깐 확인부탁해! first 5건을 위해서 따로 Pageable을 주입하는 식으로 하고있어 이전에는 메서드 2개를 사용했는데 지금은 하나의 메서드로 돌려쓰고있어

2021-10-01 06:15 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
> +    public void addGivenDonation(Donation donation) {
맞어 메서드 네이밍도 너무 애매했어!! donate, receiveDonation 좋은 것 같다 반영해둘게~!

2021-10-01 06:18 UTC, DWL5 commented on server/src/main/java/com/example/tyfserver/donation/repository/DonationRepository.java
> -    List<Donation> findFirst5ByMemberAndStatusNotOrderByCreatedAtDesc(Member member, DonationStatus status);
오호 다시 한번 봐볼게!!

2021-10-01 15:45 UTC, Be-poz commented
로키꺼 들고와서 적용시켜놨습니다~! 중간중간 함정이 있어서 abort merge 2번했따...

2021-10-01 19:56 UTC, Rok93 approved these changes
파즈 상세한 PR 코멘트 덕분에 코드 이해하기가 한결 쉬웠어 👍
내 코드까지 가져와서 반영해놨네 전체적으로 확인했는데, Donator, Creator 나누니까 더 의미가 명확해지는 것 같다는 느낌적인 느낌(?)이 들어서 좋네 ❤️
고생했어 🙏

(함정은 내가 뭐 작업 잘못한거 있는건가...? 👀)

2021-10-02 04:57 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/common/exception/DecryptException.java
> +    ;
``EncryptException`` 에도 있었는데 여기도 있네! 처리 완료~!

2021-10-02 05:03 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/domain/Donation.java
> +    private Member donator;
응 그냥 테이블에 fk 여러개 들고 있는 식으로~~ ERD 보면 Donation 이랑 Member에 화살표 2개 연결되어있드라

2021-10-02 05:04 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/domain/Donation.java
> +    }
아 요거는 처음에 Donation에 Member 2개 넣을 때에 뭐 오류 자꾸떠서 추가해줬던거였는데 id로 어차피 식별되어야하는게 맞으니깐 삭제안하고 뒀어! ``@Id`` 붙인다고 객체에서 알아서 동등성 판별해주지는 않을걸.. ?(불확실 ㅎ)

2021-10-02 05:10 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> +        creator.receiveDonation(savedDonation);
> (함정은 내가 뭐 작업 잘못한거 있는건가...? 👀)

요거는 풀 받았을 때 단순히 내거를 택하거나 로키거 택하면 안되고 두개 섞어야 하는 경우가 있었어 가지구 ㅋㅋㅋ DonationSTatus랑 Member 필드명 변경때문에

2021-10-02 06:09 UTC, DWL5 approved these changes
파즈 저번에 한번 코드 봤고, 이해한되던 부분 코멘트 단 것도 이번에 한번 봐봤어!!

너무 잘구현해줘서 따로 리뷰할게 없다!!
고생했어 👏

2021-10-02 13:33 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> +                donationRepository.findDonationByCreatorOrderByCreatedAtDesc(findMember, PageRequest.of(0, 5))
예쓰~! 추가 리뷰달았었구낭 ㅋㅋㅋ 못봐서 톡으로 리뷰 끝난거냐고 물어본거였으 🙇‍♂️

2021-10-02 15:41 UTC, Joyykim requested changes
수고했어 파즈😀
분리 작업이 크지 않아서 다행이네👍👍👍
꼼꼼하게 코멘트 써줘서 수월하게 리뷰했고, 공부도 됐어. 고마워!❤️

몇가지 수정해야할 부분이 있어. 반영후에 리뷰 다시 해줄게!
테스트 코드는 아직 DonationServiceTest 만 봤는데, 내일 나머지 보고 더 리뷰해줄게👍

2021-10-02 15:41 UTC, Joyykim commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
>      }
`@Transactional` 때문에 롤백되서 delete 안해줘도 되지 않아?

2021-10-02 15:41 UTC, Joyykim commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
> +        em.clear();
flush, clear 안해도 테스트는 통과하긴 하는데, `donationService.createDonation()`안에서 작업한거 db에 제대로 날리고 나서 확인하려고 하는거지? 👍

2021-10-03 07:16 UTC, Joyykim requested changes
테스트도 리뷰 추가!!

2021-10-03 07:50 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/domain/Donation.java
> +    public void to(final Member creator) {
좋다! 이걸 왜 생각못했지 굿 반영할게~!

2021-10-03 07:53 UTC, Joyykim requested changes

2021-10-03 07:53 UTC, Joyykim commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
> +    private final List<Donation> givingDonations = new ArrayList<>();
`givenDonations`, `givingDonations` 는 바꾸는게 어떨까?

일단 givenDonations 은 문법적으로 **(내가) 준 도네이션들**이라고 해석할 듯(과거분사)! 만약 수동태(주어진 도네이션)을 의도했더라도 이게 내가 받은거라고 해석하긴 어렵다고 생각해.
`receiveDonation()` 과 매칭도 할겸 `recievedDonations`로 바꾸면 어떨까?
(`receiveDonation()`는 다른 메서드와 합쳐도 될 것 같다는 리뷰를 위에서 하긴 했지만 receive라는 네이밍은 맘에 들거든)
**givenDonations -> recievedDonations**

givingDonations은 `후원을 주는 것`이라는 행위라고 헷갈릴 것 같아. (ing 동명사)
위의 recieved와 같이 과거분사를 써서 통일성있게 가면 될 것 같아.
**givingDonations -> givenDonations**

그리고 만약 맞는 문법이었어도 두 변수명이 너무 유사해서 헷갈릴 것 같아

**결론**
```
receivedDonations // 창작자로서 받은 도네이션들
givenDonations // 후원자로서 준 도네이션들
```

2021-10-03 08:47 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> +        creator.increasePoint(donationRequest.getPoint());
이거는 기존의 잔재 때문에 착각한 것 같네. 이전에는 포인트를 비회원한테 받으면 회원(창작자)의 포인트에 쌓이게 되고 이것을 출금하는 식이었으니깐 이거를 그대로 들고간거였는데, 이제는 아예 별개니깐 빼야겠다. 주는 포인트랑 받는 후원에 대한 포인트는 별개인게 맞지 ?? 일단 바꿔놓을게

2021-10-03 08:56 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> +        creator.increasePoint(donationRequest.getPoint());
![image](https://user-images.githubusercontent.com/45073750/135746656-4e196ad2-4268-409f-be8c-ccc3c9582cbc.png)
충전 시에 member의 ``addAvailablePoint`` 호출하고 있었는데 내부 로직은  
![image](https://user-images.githubusercontent.com/45073750/135746663-52701fea-3494-4a20-b9cc-751b3bd1d574.png)
이거인데 ``increasePoint``랑 겹쳐서 삭제하고 충전 시에 ``increasePoint`` 호출하게끔 변경했어!  

이 부분 availablePoint 이게 그 이전의 잔재 같은거였네.. 이것과 관련해서 어제 프론트에서 db 터졌던걸 경험했던 거였고!(db 업뎃을 안해서)  

요거 진짜 잘 잡아준 것 같음! 조이가 나중에 직접 단톡에서 말하면 좋을 것 같아! 나도 크게 착각하고 있었다. 후원을 받으면 포인트가 올라가는걸로 이거 진짜 좋다 굿굿 정말 중요한 내용인 것 같아! 👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

2021-10-03 08:56 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
>      public void addAvailablePoint(Long amount) {
엇 여기 있었네! ㅋㅋㅋㅋㅋ 이거 적용해놨어! 또 비슷한 생각했네

2021-10-03 08:59 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
> +    }
이 부분은 살짝 다르게 해놨어! 처음엔 나도 위의 코드 처럼 했었는데 그러면 테스트 깨지는 곳이 좀 생기고 그것들 수정하고 신경써줘야 할 곳이 생겨버려서, 테스트 안깨지게끔 기존과 같이 돌아가지만 ``donate`` 하나로 처리할 수 있게끔 해놨어!  
![image](https://user-images.githubusercontent.com/45073750/135746796-a9095d2c-a2f4-48db-af33-6d903a522f94.png)
포인트 증가, 감소, from, to 를 Donation의 ``donate`` 메서드 하나로 처리해놨구,  
![image](https://user-images.githubusercontent.com/45073750/135746818-69babb5c-4202-4df1-ab8f-66098e391241.png)
![image](https://user-images.githubusercontent.com/45073750/135746826-89c3e61e-9446-4405-ab1c-a89c14d9136e.png)
이렇게 해놨어

2021-10-03 09:26 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
> +        if (this.getGivingDonations().contains(donation)) {
없음! 습관적으로 씀. .!!! 바꿀게!

2021-10-03 09:27 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/domain/Donation.java
> +    }
이거 Member 클래스의 ``validateMemberGivingDonation`` 에서 contains 확인할 때에 필요하닷

2021-10-03 09:31 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/member/exception/WrongDonationOwnerException.java
> +    public static final String ERROR_CODE = "donation-005";
이건느 우리 API 문서에서 004가 표기되어있어서 005를 썼어! 근데 지금 004가 비어져있네! 그래두 그대로 건너뛰고 005 쓰는게 좋다구 생각해! 만약 프론트에서 004를 쓰는데 백에서 004가 사라진 경우 가정했을 때,  
1. 백에서 새로운 익셉션을 004로 쓰는 경우  
 - 작동이 제대로 됨. 근데 프론트는 004 익셉션을 예상했지만 실제로는 005에 대한 익셉션 alert? 임  
2. 건너뛰는 경우
 - 거기서 ERROR_CODE로 판별할테니깐 004에 대한 값이 아니기 때문에 문제있다는 것을 식별할 수 있음! 

라고 생각해서 005 그냥 두는게 좋을 것 같아!

2021-10-03 09:34 UTC, Be-poz commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
>      }
``tearDown`` 초기 메서드는 내가 작업한 부분이 아니여서 기존의 흐름을 그냥 그대로 따라가려고 ``memberRepository.delete(creator)`` 를 추가해준거야!

2021-10-03 09:36 UTC, Be-poz commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
> +        em.clear();
응 그렇지! 저거 안날리고 기존의 객체를 가지고 테스트하게되면 db에 실제로 날리고 있지 않아도 테스트는 통과될거야  
로직 안에서 해당 객체내에 우리가 직접 add 해준다던지 set 해준다던지 하기 때문에 db에 안날라가도 테스트 통과할 수 있기 때문에, flush, clear 해준 다음에 db에서 값을 불러서 진짜 제대로 들어갔는지 확인해준거야!!  

이런 작업 때문에 예전에 service layer에 대한 테스트를 단위 테스트에서 통합 테스트로 바꿨던 거였어!

2021-10-03 09:37 UTC, Be-poz commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
> +        DonationMessageRequest messageRequest = new DonationMessageRequest("secretMessage", true);
이 부분은 기존에 호출하는 메서드가 메세지에 대한 정보를 비공개 처리하지 않고 그냥 불러오기 때문에 테스트를 스킵한거였는데 확실한게 좋은거니깐 테스트 추가해둘게~!

2021-10-03 09:49 UTC, Be-poz commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
> +        DonationMessageRequest messageRequest = new DonationMessageRequest("secretMessage", true);
맞다!! 테스트 추가할게~!

2021-10-03 09:57 UTC, Be-poz commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
> +        DonationResponse donationResponse = donationService.createDonation(request, donator.getId());
완룟

2021-10-03 09:58 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
> +    private final List<Donation> givingDonations = new ArrayList<>();
요거는 코멘트 남긴대로 나도 일단 해둔거라서 조이 의견 좋은 것 같어! 이거 정말 애매했어서 ... 바꿔놓을게~!

2021-10-03 10:02 UTC, Be-poz commented
조이 피드백 다 반영했어~! 꼼꼼한 피드백 고마워!!

2021-10-03 10:02 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
> +    private final List<Donation> givingDonations = new ArrayList<>();
네이밍 정하면서도 given giving 굉장히 이상했는데 아주 맘에드는군

2021-10-03 10:44 UTC, Joyykim commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> +        creator.increasePoint(donationRequest.getPoint());
> 이전에는 포인트를 비회원한테 받으면 회원(창작자)의 포인트에 쌓이게 되고 이것을 출금하는 식이었으니깐 이거를 그대로 들고간거였는데, 이제는 아예 별개니깐 빼야겠다.

맞아맞아👍

> 주는 포인트랑 받는 후원에 대한 포인트는 별개인게 맞지 ??

후원에 대한 포인트가 정확히 어떤걸 말하는 거야? 멤버의 포인트 필드? 아님 도네이션의 포인트 필드? 혹시 이전의 멤버가 가지고 있던 후원할때 쓰는 포인트, 후원 받은 포인트를 말하는거야?

2021-10-03 11:00 UTC, Joyykim commented on server/src/main/java/com/example/tyfserver/member/domain/Member.java
> +    }
고생했어!근데 테스트 많이 깨지나ㅠ
난 저러면 from to를 쓸수도 잇고 donateDontions, recieve... 을 쓸수도있고 donate를 쓸수도있으니까 실수할 여지가 많을것같다는 생각이 드네!
그리고 도네이션에서 donate를 했을때 멤버에 갔다가 다시 도네이션을 가는 흐름이 조금 복잡하다는 생각도 들어!

근데 테스트가 너무 깨지면 고치는데도 오래걸리니까 만약 작업할거라면 이슈남기고 다음 pr에 하면 될거같애.

2021-10-03 11:02 UTC, Joyykim commented on server/src/main/java/com/example/tyfserver/member/exception/WrongDonationOwnerException.java
> +    public static final String ERROR_CODE = "donation-005";
예전에 쓰던 error code 였구나. 그렇다면 새로 하는게 맞지!👍👍

2021-10-03 11:40 UTC, Be-poz commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> +        creator.increasePoint(donationRequest.getPoint());
아냐아냐 내가 헷갈리게 말했네. 도네이션으로 받은 포인트는 따로 Member에 필드로 없고 그냥 정산 탭에서 정산가능한 금액에 대한 api 호출할 때나 계산하는거니깐! 무시해두돼

2021-10-03 12:56 UTC, Joyykim approved these changes
고생했어 파즈!!!!!!

2021-10-03 12:56 UTC, Joyykim commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> -        donator.reducePoint(donationRequest.getPoint());
`Member#donateDonation()` 안에서 해주는구나!

2021-10-03 12:56 UTC, Joyykim commented on server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
>      }
```suggestion
    private DonationResponse createDonation(Member member, Long point) {
        DonationRequest request = new DonationRequest(member.getPageName(), point);
        return donationService.createDonation(request, member.getId());
    }
```
이런 느낌 얘기한건데ㅎㅎ

2021-10-03 13:02 UTC, merged

2021-10-03 14:30 UTC, Rok93 commented on server/src/main/java/com/example/tyfserver/donation/service/DonationService.java
> +        creator.receiveDonation(savedDonation);
에구구... 생각보다 단순한게 아니였네 🥲

2021-10-03 14:32 UTC, Rok93 commented on server/src/main/java/com/example/tyfserver/donation/domain/Donation.java
> +    public void to(final Member creator) {
오 from, to 따로 두지 말고 하나로 묶는거 좋다!!