feat(client): 설정페이지, 이메일란(수정불가) 추가
woowacourse-teams/2021-tyf pull request #426
Opened 2021-10-02 07:43 UTC by jho2301

2021-10-06 06:21 UTC, hchayan requested changes

2021-10-06 06:21 UTC, hchayan commented on client/main/src/components/Setting/UserSettingForm/UserSettingForm.tsx
> +        <Input value={userInfo?.email} readOnly />
readOnly면 아래처럼 보이는데
![image](https://user-images.githubusercontent.com/11311739/136150529-bc8a9d1f-6299-47f1-ad4a-b4b455adcc9e.png)

disabled로 하면 아래처럼 보이고 클릭시 변화도 없어서 더 좋을듯 ㅇㅇ
![image](https://user-images.githubusercontent.com/11311739/136150810-79bf10c8-7209-4796-aa26-0c5c0042cb82.png)

2021-10-08 13:31 UTC, jho2301 commented on client/main/src/components/Setting/UserSettingForm/UserSettingForm.tsx
> +        <Input value={userInfo?.email} readOnly />
백그라운드 회색껴서 전자가 더 깔끔하지 않아? 어차피 조작안되는건 둘다 같구

2021-10-10 06:02 UTC, hchayan commented on client/main/src/components/Setting/UserSettingForm/UserSettingForm.tsx
> +        <Input value={userInfo?.email} readOnly />
현재 입력칸 focus하면 focus 빨간 밑줄 효과까지 들어가 있어서
사용자 입장에서 오류라 생각되는거같아

그러면 저 input focus 효과에 대해 overwrite 해주면 좋을꺼같아.

2021-10-14 11:20 UTC, jho2301 commented on client/main/src/components/Setting/UserSettingForm/UserSettingForm.tsx
> +        <Input value={userInfo?.email} readOnly />
![image](https://user-images.githubusercontent.com/44419181/137307709-5a85e778-d869-4f98-83fa-c629f41b637f.png)

1. 이미 도네이션 메시지 입력 화면에서 readOnly 처리가 되어있어서 일관성차원에서도 유지하는게 나을듯!

2. 우리 focus효과가 진홍색 밑줄이어서 이거는 focus UI의 문제로 봐야할건데, 우리모두 이상없다고 합의를 봤기때문에 괜찮다구 생각해

2021-10-14 12:44 UTC, merged