[#30] 후원자 후원 마크업 구현
woowacourse-teams/2021-tyf pull request #46
Opened 2021-07-11 08:15 UTC by jho2301

금액 선택 페이지
응원 메세지 페이지
후원 완료 페이지

![image](https://user-images.githubusercontent.com/44419181/125187621-765b3900-e26b-11eb-8360-a968e0d15140.png)

후원완료페이지 금액이랑 이름부분이 가변적이라 세줄로 일단 구분해봤어
내일 다시 이야기해봅시다

2021-07-11 08:16 UTC, jho2301 commented
이모지 자체가 흔들리는 애니메이션 떠올랐는데 좋은듯 딸깍딸깍?

2021-07-11 08:17 UTC, jho2301 commented
아이디어: 아래 두 개버튼을 모바일에선 화면 최하단으로 배치하는게 좋을듯

2021-07-11 08:31 UTC, yujo11 commented
가로 세로 화면 별로 테스트 끝난건가요?

아까 옆에서 보니 width가 320px일 때 깨지는거 같던데... 음... 🤔🤔🤔🤔🤔🤔🤔

2021-07-12 00:55 UTC, hchayan commented
처음에 흔들리고 그 이후엔 터치해야 흔들리는것도 좋을듯!

2021-07-12 01:13 UTC, hchayan requested changes

2021-07-12 01:13 UTC, hchayan commented on client/src/pages/Donation/Message/DonationMessagePage.tsx
> +const DonationMessagePage: VFC = () => {
이거는 그냥 `VFC<HTMLAttributes<HtmlElements>>` 안붙여도 되나??

2021-07-12 01:13 UTC, hchayan commented on client/src/pages/Donation/Success/DonationSuccessPage.styles.ts
> +
띄어쓰기

2021-07-12 01:29 UTC, jho2301 commented on client/src/pages/Donation/Message/DonationMessagePage.tsx
> +const DonationMessagePage: VFC = () => {
얍얍 props안받으면 상관없으

2021-07-12 03:25 UTC, hchayan approved these changes

2021-07-12 03:25 UTC, merged