[#66] 메인페이지 창작자 리스트 보여주기
woowacourse-teams/2021-tyf pull request #68
Opened 2021-07-14 09:04 UTC by jho2301

api 엔드포인트 확정안나서 임시로 넣어놨고 나중에 바꿔야해

2021-07-14 17:45 UTC, hchayan requested changes
내가 못본건지 모르겠는데 창작자 리스트 보여주는거 tdd 테스트도 하면 좋을거같음!

2021-07-14 17:45 UTC, hchayan commented on client/src/components/Main/CreatorList/CreatorList.tsx
> +  const { creatorList } = useCreatorList();
`useCreatorList` 라는 네이밍 보단 좀더 추상적인 이름을 주면 어떨까? 
예를 들어 `useCreators` 같이? 더 좋은 생각 있으면 더 좋고

2021-07-14 17:45 UTC, hchayan commented on client/src/types.ts
> +  profileImgSrc: string;
`src` 없어도 괜찮을듯?

2021-07-14 17:45 UTC, hchayan commented on client/src/types.ts
> +  name: string;
`nickname` 으로 통일하자

2021-07-14 17:45 UTC, hchayan commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
이거는 근데 왜 `atom` 이 아니라 `selector`를 쓴거야??

2021-07-14 17:45 UTC, hchayan commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
또 `atom`도 뒤에 `-query` suffix 붙일꺼야??

2021-07-14 17:45 UTC, hchayan commented on client/src/pages/Main/MainPage.tsx
> +        <ErrorBoundary fallback={<h2>창작자 목록을 불러오는데 실패했습니다.</h2>}>
일단 이런느낌(범위)으로 구현해 나갈께, (page 딴에서 errorBoundary, suspense 작성하는 방식)

그리고 너가 말한 ErrorBoundary 쉽게 해주는 모듈 설치해서 쓴거같네

여기에 ErrorBoundary랑 suspense를 이런형태로 계속 쓰이면 나중에 리팩토링할때 너가 말했던것처럼 컴포넌트화 하면 좋겠다

2021-07-15 01:07 UTC, jho2301 commented on client/src/components/Main/CreatorList/CreatorList.tsx
> +  const { creatorList } = useCreatorList();
creators라는 이름을 주면 나중에 creator관련로직이 모여서 커스텀훅이 무거워지지 않을까?

2021-07-15 01:08 UTC, jho2301 commented on client/src/types.ts
> +  profileImgSrc: string;
메인페이지에  카드 구성할떄 필요해서 우선넣어놔봤는데 나중에 필요하니까 일단은 더미 이미지 패스 주면될것같은데 어떻게 생각해?

2021-07-15 01:10 UTC, hchayan commented on client/src/components/Main/CreatorList/CreatorList.tsx
> +  const { creatorList } = useCreatorList();
이건 예시고 useQurator ? 도 괜찮은데

난 그냥 List라는걸 뺏으면 좋을꺼같아서 말한거야ㅇㅇ

2021-07-15 01:10 UTC, jho2301 commented on client/src/types.ts
> +  name: string;
![image](https://user-images.githubusercontent.com/44419181/125712255-c46a6067-dc01-4632-b96d-e96f8aa73528.png)
나는 서버에서 name으로오는걸로 확인했는데 한 번 다시 이야기해보면 좋을듯

2021-07-15 01:11 UTC, hchayan commented on client/src/types.ts
> +  profileImgSrc: string;
아 그정확히는 네이밍에서 img까지만있고 src라는 글자는 없었으면 좋을꺼같다한거야!

2021-07-15 01:12 UTC, jho2301 commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
atom은 State가 붙는게 좋은듯

2021-07-15 01:12 UTC, jho2301 commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
atom도 비동기통신이 되남?

2021-07-15 01:12 UTC, hchayan commented on client/src/types.ts
> +  name: string;
그거 어제 네이밍 통일하기로 얘기했던거로 기억해서 백엔드한테 한번물어봐보면좋을듯

2021-07-15 01:12 UTC, jho2301 commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
![image](https://user-images.githubusercontent.com/44419181/125712439-c93f7bb8-1a41-46ab-b475-30544d10caf3.png)
이건 공식문서 스샷

2021-07-15 01:14 UTC, jho2301 commented on client/src/pages/Main/MainPage.tsx
> +        <ErrorBoundary fallback={<h2>창작자 목록을 불러오는데 실패했습니다.</h2>}>
리팩토링할때 이야기해보즈아 
https://jbee.io/react/error-declarative-handling-1/#%EB%B9%84%EB%8F%99%EA%B8%B0-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-wrapper
위에는 아이디어 얻은 링크

2021-07-15 01:15 UTC, hchayan commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
> atom은 State가 붙는게 좋은듯

좋아 👌

2021-07-15 01:17 UTC, jho2301 commented on client/src/components/Main/CreatorList/CreatorList.tsx
> +  const { creatorList } = useCreatorList();
음 나는 List가 더 명시적인것같아 
Qurator는 창작자를 큐레이션한다는 것에서 큐레이션이 들어가면 의미전달이 어려울 것 같고
creators랑 creatorList중에 고민해봐야할듯

2021-07-15 01:17 UTC, hchayan commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
> atom도 비동기통신이 되남?

돼는줄알았는데 다시보니까 atom안에 selector 가 있는거엿네

그리고 다시생각해봣는데 목적에도 selector가 맞긴한듯..
그런데 궁금하게 이렇게하면 다시 재요청보내는건 어떻게해?

2021-07-15 01:18 UTC, jho2301 commented on client/src/types.ts
> +  profileImgSrc: string;
src가 들어가는게 문자열의 의미가 더 잘살지 않을까?? Img만들어가면 Img 앨리먼트로 알 수도 있을것 같아

2021-07-15 01:18 UTC, jho2301 commented on client/src/types.ts
> +  name: string;
오키 확정나면 통일하자

2021-07-15 01:19 UTC, jho2301 commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
requestId 같은 atom을 만들어서 의존하게한다음
requestId값을 변경해주는 식으로 하더라

2021-07-15 01:23 UTC, jho2301 commented
기능이 c*ud랑 관계 없는 단순 fetch라서 테스트가 의미가 적은 것 같아서 뺐는데 하는게 더 좋을까?  @hchayan

2021-07-15 01:27 UTC, hchayan commented
> 기능이 c*ud랑 관계 없는 단순 fetch라서 테스트가 의미의 적은 것 같아서 뺐는데 하는게 더 좋을까? @hchayan

그래도 로딩해서 보이는지정도 테스트는 있어도 괜찮다생각해서 ㅇㅇ
없어도 큰 문제는없을듯? 너말대로 조작기능이 아니니까ㅇㅇ

2021-07-15 01:28 UTC, hchayan commented on client/src/components/Main/CreatorList/CreatorList.tsx
> +  const { creatorList } = useCreatorList();
ㅇㅋㅇㅋ 그럼 일단 이대로 진행하자

2021-07-15 01:30 UTC, hchayan commented on client/src/types.ts
> +  profileImgSrc: string;
> src가 들어가는게 문자열의 의미가 더 잘살지 않을까?? Img만들어가면 Img 앨리먼트로 알 수도 있을것 같아

그래? 난 너무 세세하게 가는거 아닌가해서 그랬는데 그게 목적인거면 괜찮을듯

2021-07-15 01:33 UTC, hchayan commented on client/src/service/state/creator.ts
> +export const creatorListQuery = selector<Creator[]>({
얘도 결국 흐름때문에 큰 의미없는걸 만들어줘야되네
좋아 이해했어 땡큐 👍👍👍

2021-07-15 01:40 UTC, jho2301 commented
ㅇㅋㅇㅋ 테스트 만들어서 넣어볼게

2021-07-15 06:49 UTC, hchayan approved these changes

2021-07-15 06:49 UTC, merged